# This rule is not used by the project pod-labeler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to labels.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pod-labeler
    app.kubernetes.io/managed-by: kustomize
  name: podlabeler-viewer-role
rules:
- apiGroups:
  - labels.example.com
  resources:
  - podlabelers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - labels.example.com
  resources:
  - podlabelers/status
  verbs:
  - get
