# This rule is not used by the project pod-labeler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over labels.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pod-labeler
    app.kubernetes.io/managed-by: kustomize
  name: podlabeler-admin-role
rules:
- apiGroups:
  - labels.example.com
  resources:
  - podlabelers
  verbs:
  - '*'
- apiGroups:
  - labels.example.com
  resources:
  - podlabelers/status
  verbs:
  - get
