# This rule is not used by the project controller-example itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over sync.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller-example
    app.kubernetes.io/managed-by: kustomize
  name: configmapsync-admin-role
rules:
- apiGroups:
  - sync.example.com
  resources:
  - configmapsyncs
  verbs:
  - '*'
- apiGroups:
  - sync.example.com
  resources:
  - configmapsyncs/status
  verbs:
  - get
